import type { Metadata } from "next";
import "./globals.css";
import TopNav from "@/components/navbar/TopNav";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <TopNav />
        <main className="container mx-auto p-10">{children}</main>
      </body>
    </html>
  );
}
